export const BTN__PRIMARY__SOLID = "BTN__PRIMARY__SOLID";
export const BTN__WARNING__SOLID = "BTN__WARNING__SOLID";
export const BTN__DANGER__SOLID = "BTN__DANGER__SOLID";
export const BTN__SUCCESS__SOLID = "BTN__SUCCESS__SOLID";
export const BTN__PRIMARY__OUTLINE = "BTN__PRIMARY__OUTLINE";
export const BTN__WARNING__OUTLINE = "BTN__WARNING__OUTLINE";
export const BTN__DANGER__OUTLINE = "BTN__DANGER__OUTLINE";
export const BTN__SUCCESS__OUTLINE = "BTN__SUCCESS__OUTLINE";

export const BTN__SMALL = "BTN__SMALL";
export const BTN__MEDIUM = "BTN__MEDIUM";
export const BTN__LARGE = "BTN__LARGE";
